Project/ShopOnline/ShopOnline/Models/InvoinceDetail.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoinceDetail
    {
        public string invoinceNo { get; set; }
        public int productId { get; set; }
        public Nullable<int> quanlityProduct { get; set; }
        public Nullable<int> unitPrice { get; set; }
        public Nullable<int> totalPrice { get; set; }
        public Nullable<int> totalDiscount { get; set; }
    
        public virtual Invoince Invoince { get; set; }
        public virtual Product Product { get; set; }
    }
}

Project/ShopOnline/ShopOnline/Areas/Admin/Controllers/DashBoardController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using ShopOnline.Models;

namespace ShopOnline.Areas.Admin.Controllers
{
    [Authorize]
    public class DashBoardController : Controller
    {
        menfashionEntities db = new menfashionEntities();
        public ActionResult Index()
        {
            /*---------------------------------------THỐNG KÊ------------------------------*/
            // Lấy ra tổng số tiền các đơn hàng - lợi nhuận
            ViewBag.profit = db.InvoinceDetails.Sum(model => model.totalPrice);
            // Lấy ra tổng số lượng các user khách hàng đang có trong database - tổng số tài khoản hiện tại
            ViewBag.users = db.Members.Where(model => model.roleId == 3).Count();
            // Lấy ra tổng số các đơn đặt hàng đang có trong database - tổng số đơn hàng 
            ViewBag.orders = db.Invoinces.Count();
            // Lấy số lượng người truy cập từ Application đã tạo
            ViewBag.SoNguoiTruyCap = HttpContext.Application["SoNguoiTruyCap"].ToString();
            return View();
        }
        public PartialViewResult Chart()
        {

            // Danh thu sản phẩm cao nhất, thu được:
            /*(tên sản phẩm - hình ảnh - tổng danh thu dựa trên đơn hàng)*/
            var getTopProduct = (db.Products.Join(db.InvoinceDetails,
                                sanPham => sanPham.productId,
                                ctDonHang => ctDonHang.productId,
                                (sanPham, ctDonHang) => new {
                                    tensanpham = sanPham.productName,
                                    hinh = sanPham.image,
                                    gia = ctDonHang.quanlityProduct * sanPham.price,
                                })).ToList();
            var test = getTopProduct;

            // Đếm số lượng sản phẩm trong từng loại sản phẩm, thu được: (Đã đổ dữ liệu vào pie-chart)
            /*(tên loại sản phẩm - số lượng sản phẩm thuộc loại đó)*/
            var countProductOfCategory = (from c in db.ProductCategories
                                          join p in db.Products on c.categoryId equals p.categoryId into temp1
                                          from temp2 in temp1.DefaultIfEmpty()
                                          group temp2 by c.categoryName into grouped
                                          select new
                                          {
                                              ten = grouped.Key,
                                              count = grouped.Count(t => t.productId != null)
                                          }).ToList();
            var categoriesData = countProductOfCategory;

            List<string> categories = new List<string>();
            List<string> categoriesCount = new List<string>();
            foreach (var i in categoriesData)
            {
                categories.Add(i.ten);
            }
            foreach (var i in categoriesData)
            {
                categoriesCount.Add(i.count.ToString());
            }
            ViewBag.categories = categories.ToList();
            ViewBag.categoriesCount = categoriesCount.ToList();

            // Thống kê doanh thu bán hàng theo ngày, thu được: (Đã đổ dữ liệu vào Line-chart)
            /*(ngày bán - doanh thu)*/
            
            var doanhthu = db.vDoanhThuTheoNgays.OrderByDescending(model => model.dateOrder).Take(7).ToList(); // Sắp xếp giảm dần theo ngày và lấy 7 ngày gần nhất
            // Đảo ngược mảng để hiển thị ngày theo thứ tự tăng dần
            doanhthu.Reverse();

            List<string> date = new List<string>();
            List<int> income = new List<int>();
            foreach (var i in doanhthu)
            {
                date.Add(i.dateOrder);
            }
            foreach (var i in doanhthu)
            {
                income.Add((int)i.income);
            }
            ViewBag.date = date.ToList();
            ViewBag.income = income.ToList();
            // Chart
            return PartialView();
        }
        public PartialViewResult InvoinceList() // Danh sách hóa đơn trong ngày
        {
            var list = db.vHoaDonTrongNgays.OrderByDescending(model => model.dateOrder).ToList();
            return PartialView(list);
        }
        public ActionResult TrackingCovid()
        {
            return View();
        }        
        public ActionResult Chat()
        {
            return View();
        }
        [HttpGet]
        public ActionResult EditProfie(string userName)
        {
            Member member = db.Members.Find(userName);
            Session["imgPath"] = member.avatar;
            return View(member);
        }
        [HttpPost]
        public ActionResult EditProfie(Member member, HttpPostedFileBase uploadFile)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (uploadFile != null)
                    {
                        var fileName = Path.GetFileName(uploadFile.FileName);
                        var path = Path.Combine(Server.MapPath("~/Content/img/avatar"), fileName);

                        member.avatar = "~/Content/img/avatar/" + fileName;
                        db.Entry(member).State = EntityState.Modified;

                        string oldImgPath = Request.MapPath(Session["imgPath"].ToString()); // Lấy đường dẫn ảnh (absolute path)
                        var avatarName = Session["imgPath"].ToString(); // Lấy đường dẫn ảnh (relative path)
                        var checkAvatart = db.Members.Where(model => model.avatar == avatarName).ToList(); // Kiểm tra ảnh có trùng với avatar của member nào không

                        if (db.SaveChanges() > 0)
                        {
                            uploadFile.SaveAs(path);
                            if (System.IO.File.Exists(oldImgPath) && checkAvatart.Count < 2) // Nếu tồn tại hình trong folder và không member nào có hình này thì xóa ra khỏi folder
                            {
                                System.IO.File.Delete(oldImgPath);
                            }
                            var info = db.Members.Where(model => model.userName == member.userName).SingleOrDefault();
                            Session["infoAdmin"] = info; // Lấy thông tin mới của member lưu lại vào session hiển thị
                            return RedirectToAction("Index");
                        }

                    }
                    else
                    {
                        member.avatar = Session["imgPath"].ToString();
                        db.Entry(member).State = EntityState.Modified;
                        if (db.SaveChanges() > 0)
                        {
                            var info = db.Members.Where(model => model.userName == member.userName).SingleOrDefault();
                            Session["infoAdmin"] = info;
                            return RedirectToAction("Index");
                        }
                    }
                }
                ViewBag.roleId = new SelectList(db.Roles, "roleId", "roleName", member.roleId);
                return View(member);
            }
            catch (Exception ex)
            {
                TempData["msgEditProfieFailed"] = "Edit failed! " + ex.Message;
                return RedirectToAction("Index");
            }
        }
        [HttpGet]
        public ActionResult ChangePassword(string userName)
        {
            Member member = db.Members.Find(userName);
            return View(member);
        }
        [HttpPost]
        public ActionResult ChangePassword(Member member, FormCollection collection)
        {
            try
            {
                var CurrentPassword = collection["CurPassword"]; // Mật khẩu hiện tại
                var NewPassword = collection["NewPassword"]; // Mật khẩu mới
                //var ConfirmPassword = collection["Confirm"];

                CurrentPassword = Encryptor.MD5Hash(CurrentPassword.Trim());
                NewPassword = Encryptor.MD5Hash(NewPassword.Trim());

                var check = db.Members.Where(model => model.password == CurrentPassword && model.userName == member.userName).FirstOrDefault();
                if (check!= null)
                {
                    check.password = NewPassword;
                    db.SaveChanges();
                    TempData["msgChangePassword"] = "Successfully change password!";
                    return RedirectToAction("index");
                }
                else
                {
                    ModelState.AddModelError("", "Incorrect your password!");
                    return View(member);
                }
                return View(member);
            }
            catch(Exception ex)
            {
                TempData["msgChangePasswordFailed"] = "Edit failed! " + ex.Message;
                return RedirectToAction("Index");
            }
        }
    }
}

Project/ShopOnline/ShopOnline/Areas/Admin/Views/DashBoard/ChangePassword.cshtml
@model ShopOnline.Models.Member
@{
    ViewBag.Title = "ChangePassword";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutDashBoard.cshtml";
}


<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body" style="position: relative; left: 266px;">
                    <h4 class="card-title">Edit Profie</h4>
                    @using (Html.BeginForm("ChangePassword", "DashBoard", FormMethod.Post, new { @id = "form-1", @enctype = "multipart/form-data" }))
                    {
                        @Html.AntiForgeryToken()
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-body">
                            @Html.HiddenFor(model => model.dateOfJoin)
                            @Html.HiddenFor(model => model.status)
                            @Html.HiddenFor(model => model.roleId)
                            @Html.HiddenFor(model => model.userName)
                            @Html.HiddenFor(model => model.firstName)
                            @Html.HiddenFor(model => model.lastName)
                            @Html.HiddenFor(model => model.email)
                            @Html.HiddenFor(model => model.identityNumber)
                            @Html.HiddenFor(model => model.phone)
                            @Html.HiddenFor(model => model.address)
                            @Html.HiddenFor(model => model.birthday)
                            @Html.HiddenFor(model => model.avatar)


                            <div class="form-group">
                                @Html.EditorFor(model => model.userName, new { htmlAttributes = new { @class = "form-control", @id = "userName", @type = "hidden" } })
                            </div>


                            <div class="form-group">
                                <label for="userName">Current password</label>
                                <input type="password" class="form-control" id="current-password" name="CurPassword"/>
                                <span class="form-message"></span>
                            </div>
                            <div class="form-group">
                                <label for="productName">New password</label>
                                <input type="password" class="form-control" id="new-password" name="NewPassword"/>
                                <span class="form-message"></span>
                            </div>
                            <div class="form-group">
                                <label for="productName">Confirm password</label>
                                <input type="password" class="form-control" id="password_confirmation" name="Confirm"/>
                                <span class="form-message"></span>
                            </div>
                        </div>
                        <div class="form-actions">
                            <div class="text-left">
                                <button type="submit" class="btn btn-info">Submit</button>
                                <button type="reset" class="btn btn-dark">Reset</button>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>
<style>
    .form-group input{
        width: 50%
    }
</style>
<script src="~/Content/js/validator.js"></script>
<script>
    Validator({
        form: '#form-1',
        formGroupSelector: '.form-group',
        errorSelector: '.form-message',
        rules: [

            Validator.isRequired('#current-password'),
            Validator.minLength('#new-password', 6),
            Validator.isConfirmed('#password_confirmation', function () {
                return document.querySelector('#form-1 #new-password').value;
            }, 'Passwords must match')
        ],
    });
</script>

Project/ShopOnline/ShopOnline/Areas/Admin/Views/DashBoard/Chart.cshtml
<script>
    var categories = @Html.Raw(Json.Encode(ViewBag.categories));
    var categoriesCount = @Html.Raw(Json.Encode(ViewBag.categoriesCount));
    new Chart(document.getElementById("pie-chart"), {
        type: 'doughnut',
        data: {
            labels: categories,
            datasets: [{
                label: "Population (millions)",
                backgroundColor: ["#6C7EE1", "#FBA2D0", "#2D99AE", "#BCFEFE", "#FFD66D", "#05299E", "#FFC4A4", "#F20231"],
                data: categoriesCount
            }]
        }
    });
    new Chart(document.getElementById("line-chart"), {
        type: 'line',
        data: {
            labels: ['Mon','Tue','Web','Thu','Fri','Sat','Sun'],
            datasets: [{
                label: "Income (Dollar)",
                data: [10,20,30,20,20,60,10]
            }]
        }
    });
</script>
<script>
    $(function () {
        var date = @Html.Raw(Json.Encode(ViewBag.date));
        var income = @Html.Raw(Json.Encode(ViewBag.income));
            // ==============================================================
            // Earning Stastics Chart
            // ==============================================================
            var data = {
                labels: date,
                series: [
                    income
                ]
            };

            var options = {
                axisX: {
                    showGrid: false
                },
                seriesBarDistance: 1,
                chartPadding: {
                    top: 15,
                    right: 15,
                    bottom: 5,
                    left: 0
                },
                plugins: [
                    Chartist.plugins.tooltip()
                ],
                width: '100%'
            };

            var responsiveOptions = [
                ['screen and (max-width: 640px)', {
                    seriesBarDistance: 5,
                    axisX: {
                        labelInterpolationFnc: function (value) {
                            return value[0];
                        }
                    }
                }]
            ];
            new Chartist.Line('.net-income', data, options, responsiveOptions);

            // ==============================================================
            // Visit By Location
            // ==============================================================
            jQuery('#visitbylocate').vectorMap({
                map: 'world_mill_en',
                backgroundColor: 'transparent',
                borderColor: '#000',
                borderOpacity: 0,
                borderWidth: 0,
                zoomOnScroll: false,
                color: '#d5dce5',
                regionStyle: {
                    initial: {
                        fill: '#d5dce5',
                        'stroke-width': 1,
                        'stroke': 'rgba(255, 255, 255, 0.5)'
                    }
                },
                enableZoom: true,
                hoverColor: '#bdc9d7',
                hoverOpacity: null,
                normalizeFunction: 'linear',
                scaleColors: ['#d5dce5', '#d5dce5'],
                selectedColor: '#bdc9d7',
                selectedRegions: [],
                showTooltip: true,
                onRegionClick: function (element, code, region) {
                    var message = 'You clicked "' + region + '" which has the code: ' + code.toUpperCase();
                    alert(message);
                }
            });

            // ==============================================================
            // Earning Stastics Chart
            // ==============================================================
            var chart = new Chartist.Line('.stats', {
                labels: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'], 
                series: [[11, 10, 15, 21, 14, 23, 12]]
            }, {
                low: 0,
                high: 28,
                showArea: true,
                fullWidth: true,
                plugins: [
                    Chartist.plugins.tooltip()
                ],
                axisY: {
                    onlyInteger: true,
                    scaleMinSpace: 40,
                    offset: 20,
                    labelInterpolationFnc: function (value) {
                        return (value / 1) + 'k';
                    }
                },
            });

            // Offset x1 a tiny amount so that the straight stroke gets a bounding box
            chart.on('draw', function (ctx) {
                if (ctx.type === 'area') {
                    ctx.element.attr({
                        x1: ctx.x1 + 0.001
                    });
                }
            });

            // Create the gradient definition on created event (always after chart re-render)
            chart.on('created', function (ctx) {
                var defs = ctx.svg.elem('defs');
                defs.elem('linearGradient', {
                    id: 'gradient',
                    x1: 0,
                    y1: 1,
                    x2: 0,
                    y2: 0
                }).elem('stop', {
                    offset: 0,
                    'stop-color': 'rgba(255, 255, 255, 1)'
                }).parent().elem('stop', {
                    offset: 1,
                    'stop-color': 'rgba(80, 153, 255, 1)'
                });
            });

            $(window).on('resize', function () {
                chart.update();
            });
})
</script>

Project/ShopOnline/ShopOnline/Areas/Admin/Views/DashBoard/EditProfie.cshtml
@model ShopOnline.Models.Member
@{
    ViewBag.Title = "EditProfie";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutDashBoard.cshtml";
}

<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Edit Profie</h4>
                    @using (Html.BeginForm("EditProfie", "DashBoard", FormMethod.Post, new { @id = "form-1", @enctype = "multipart/form-data" }))
                    {
                        @Html.AntiForgeryToken()
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-body">
                            <div class="row">
                                <div class="col-md-6">
                                    <img src=@Url.Content(Model.avatar) id="imagePreview" alt="image" class="rounded-circle" width="290">
                                    <input type="file" name="uploadFile" class="form-control-file" id="image" accept="image/jpeg, image/png" onclick="defaultBtnActive()" />
                                </div>
                                <div class="col-md-6">
                                    @Html.HiddenFor(model => model.dateOfJoin)
                                    @Html.HiddenFor(model => model.status)
                                    @Html.HiddenFor(model => model.roleId)
                                    @Html.HiddenFor(model => model.password)

                                    <div class="form-group">
                                        <label for="userName">Username</label>
                                        @Html.EditorFor(model => model.userName, new { htmlAttributes = new { @class = "form-control", @id = "userName", @readonly = "readonly" } })
                                        <span class="form-message"></span>
                                    </div>
                                    <div class="form-group">
                                        <label for="productName">First name</label>
                                        @Html.EditorFor(model => model.firstName, new { htmlAttributes = new { @class = "form-control", @id = "firstName" } })
                                        <span class="form-message"></span>
                                    </div>
                                    <div class="form-group">
                                        <label for="productName">Last name</label>
                                        @Html.EditorFor(model => model.lastName, new { htmlAttributes = new { @class = "form-control", @id = "lastName" } })
                                        <span class="form-message"></span>
                                    </div>
                                    <div class="form-group">
                                        <label for="productName">Email</label>
                                        @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control", @id = "email" } })
                                        <span class="form-message"></span>
                                    </div>
                                    <div class="form-group">
                                        <label for="productName">Identity number</label>
                                        @Html.EditorFor(model => model.identityNumber, new { htmlAttributes = new { @class = "form-control", @id = "identityNumber", @type = "number" } })
                                        <span class="form-message"></span>
                                    </div>
                                    <div class="form-group">
                                        <label for="productName">Phone</label>
                                        @Html.EditorFor(model => model.phone, new { htmlAttributes = new { @class = "form-control", @id = "phone", @type = "number" } })
                                        <span class="form-message"></span>
                                    </div>
                                    <div class="form-group">
                                        <label for="productName">Address</label>
                                        @Html.EditorFor(model => model.address, new { htmlAttributes = new { @class = "form-control", @id = "address" } })
                                        <span class="form-message"></span>
                                    </div>
                                    <div class="form-group">
                                        <label for="productName">Birthday</label>
                                        @Html.EditorFor(model => model.birthday, new { htmlAttributes = new { @class = "form-control", @id = "birthday", @Value = @Model.birthday.Value.Date.ToString("yyyy/MM/dd"), @placeholder ="yyyy/mm/dd" } })
                                        <span class="form-message"></span>
                                    </div>

                                </div>
                            </div>
                        </div>
                        <div class="form-actions">
                            <div class="text-right">
                                <button type="submit" class="btn btn-info">Submit</button>
                                <button type="reset" class="btn btn-dark">Reset</button>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>
<script src="~/Content/js/validator.js"></script>
<script>
    Validator({
        form: '#form-1',
        formGroupSelector: '.form-group',
        errorSelector: '.form-message',
        rules: [
            Validator.isRequired('#firstName'),
            Validator.isRequired('#lastName'),
            Validator.isEmail('#email'),
            Validator.isDate('#birthday'),
            Validator.isRequired('#identityNumber'),
            Validator.isRequired('#phone'),
            Validator.isRequired('#address'),
        ],
    });
</script>

<script>
    const inputImg = document.querySelector("#image");
    const img = document.querySelector("#imagePreview");

    function defaultBtnActive() {
        inputImg.change();
    }
    inputImg.addEventListener("change", function () {
        const file = this.files[0];
        if (file) {
            const reader = new FileReader();
            reader.onload = function () {
                const result = reader.result;
                img.src = result;
            }
            reader.readAsDataURL(file);
        }
    });
</script>

Project/ShopOnline/ShopOnline/Areas/Admin/Views/DashBoard/InvoinceDetail.cshtml
@using ShopOnline.Models
@model List<InvoinceDetail>
@{
    ViewBag.Title = "InvoinceDetail";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutDashBoard.cshtml";
}
@{ 
    Invoince info = (Invoince)@Session["infor"]; 
}
<div class="jumbotron jumbotron-fluid">
    <h1 class="mt-3 theme-color mb-4 text-center">Order detail</h1>
</div>
<div class="card-body">
    <h3 class="mb-3 text-dark text-uppercase">Information</h3>
    <hr />
    <table class="table">
        <thead class="thead-light">
            <tr>
                <th scope="col" class="text-center">Name</th>
                <th scope="col" class="text-center">Email</th>
                <th scope="col" class="text-center">Phone</th>
                <th scope="col" class="text-center">Address</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td class="text-center">
                    @if (info.customerId != null && info.userName == null)
                    {@info.Customer.firstName<span> </span>@info.Customer.lastName}
                else
                { @info.Member.firstName<span> </span>@info.Member.lastName}
                </td>
                <td class="text-center">
                    @if (info.customerId != null && info.userName == null)
                    {@info.Customer.email}
                else
                { @info.Member.email}
                </td>
                <td class="text-center">
                    @if (info.customerId != null && info.userName == null)
                    {@info.Customer.phone}
                else
                { @info.Member.phone}
                </td>
                <td class="text-center">
                    @if (info.customerId != null && info.userName == null)
                    {@info.Customer.address}
                else
                { @info.Member.address}
                </td>

            </tr>

        </tbody>
    </table>

    <h3 class="mb-3 text-dark text-uppercase">Product</h3>
    <hr />
    <table class="table">
        <thead class="thead-light">
            <tr>
                <th scope="col" class="text-center">STT</th>
                <th scope="col" class="text-center">Product</th>
                <th scope="col" class="text-center">Quality</th>
                <th scope="col" class="text-center">Unit price</th>
                <th scope="col" class="text-center">Discount</th>
                <th scope="col" class="text-center">Total money</th>
            </tr>
        </thead>
        <tbody>
            @{ int stt = 1, total = 0, totaldiscount = 0, totalprice = 0, tempPrice = 0;}
            @foreach (var i in Model)
            {
                tempPrice = (int)i.totalPrice + (int)i.totalDiscount;
                <tr>
                    <th scope="row" class="text-center font-weight-medium" width="80px">@stt</th>
                    <td width="400px">
                        <div class="row">
                            <div class="col-md-3">
                                <img src=@Url.Content("" + i.Product.image) width="80%" />
                            </div>
                            <div class="col-md-9">
                                @i.Product.productName
                            </div>
                        </div>
                    </td>
                    <td class="text-center">@i.quanlityProduct</td>
                    <td class="text-center">$@i.Product.price</td>
                    <td class="text-center">@i.Product.discount%</td>
                    <td class="text-center">$@tempPrice</td>
                </tr>
                stt++;
                total += (int)i.totalPrice;
                totaldiscount += (int)i.totalDiscount;
            }
            @{ totalprice = total + totaldiscount; }
        </tbody>
    </table>

    <h3 class="mb-3 text-dark text-uppercase">Payment</h3>
    <hr />
    <table class="table">
        <thead class="thead-light">
            <tr>
                <th scope="col" class="text-center">Total product money</th>
                <th scope="col" class="text-center">Shipping</th>
                <th scope="col" class="text-center">Total money discounted</th>
                <th scope="col" class="text-center">Total payment</th>
                <th scope="col" class="text-center">Print order</th>

            </tr>
        </thead>
        <tbody>
            <tr>
                <td class="text-center">$@totalprice</td>
                <td class="text-center">$0</td>
                <td class="text-center">-$@totaldiscount</td>
                <td class="text-center">$@total</td>
                <td class="text-center"><a href="#"><u>Print order</u></a></td>
            </tr>

        </tbody>
    </table>

</div>