Project/ShopOnline/ShopOnline/Models/InvoinceDetail.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoinceDetail
    {
        public string invoinceNo { get; set; }
        public int productId { get; set; }
        public Nullable<int> quanlityProduct { get; set; }
        public Nullable<int> unitPrice { get; set; }
        public Nullable<int> totalPrice { get; set; }
        public Nullable<int> totalDiscount { get; set; }
    
        public virtual Invoince Invoince { get; set; }
        public virtual Product Product { get; set; }
    }
}

Project/ShopOnline/ShopOnline/Areas/Admin/Controllers/CRUDinvoinceController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ShopOnline.Models;
using System.IO;
using PagedList;
using PagedList.Mvc;
using Rotativa;

namespace ShopOnline.Areas.Admin.Controllers
{
    [Authorize]
    public class CRUDinvoinceController : Controller
    {
        menfashionEntities db = new menfashionEntities();
        public ActionResult Index(int? page)
        {
            var pageNumber = page ?? 1;
            var pageSize = 10;
            var orderlist = db.Invoinces.OrderByDescending(model => model.dateOrder).Include(model => model.Member).Include(model => model.Customer).ToPagedList(pageNumber, pageSize);
            return View(orderlist);
        }
        public ActionResult InvoinceDetail(string invoinceNo)
        {

            var infor = db.Invoinces.Where(model => model.invoinceNo == invoinceNo).Include(model => model.Customer).Include(model => model.Member).FirstOrDefault();
            Session["information"] = infor;
            ViewBag.invoinceNo = invoinceNo;
            var detail = db.InvoinceDetails.Where(model => model.invoinceNo == invoinceNo).Include(model => model.Product).ToList();
            return View(detail);
        }
        public ActionResult Delete(string id)
        {
            List<InvoinceDetail> ctdh = db.InvoinceDetails.Where(model => model.invoinceNo == id).ToList();
            foreach (var i in ctdh)
            {
                db.InvoinceDetails.Remove(i);
            }
            db.SaveChanges();
            Invoince invoince = db.Invoinces.Find(id);
            db.Invoinces.Remove(invoince);
            TempData["DeleteOrder"] = "Successfully delete!";
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult DeliverySuccess(string id)
        {
            Invoince invoince = db.Invoinces.Find(id);
            invoince.deliveryDate = DateTime.Now;
            invoince.deliveryStatus = true;
            TempData["Delivery"] = "Order ID " + invoince.invoinceNo + " has been successfully delivered ";
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult ExportPDF()
        {
            return new Rotativa.ActionAsPdf("InvoinceDetail");
        }
    }
}

Project/ShopOnline/ShopOnline/Areas/Admin/Views/CRUDinvoince/Index.cshtml
@using ShopOnline.Models
@using PagedList.Mvc
@model PagedList.PagedList<Invoince>
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutDashBoard.cshtml";
}

<div class="page-breadcrumb">
    <div class="row">
        <div class="col-7 align-self-center">
            <h4 class="page-title text-truncate text-dark font-weight-medium mb-1">Orders manage</h4>
            <div class="d-flex align-items-center">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb m-0 p-0">
                        <li class="breadcrumb-item"><a href="~/Admin/DashBoard/Index">Dash board</a></li>
                        <li class="breadcrumb-item active">Orders list</li>
                    </ol>
                </nav>
            </div>
        </div>
        <div class="col-5 align-self-center">
            <div class="customize-input float-right">
                <select class="custom-select custom-select-set form-control bg-white border-0 custom-shadow custom-radius">
                    <option selected>Aug 19</option>
                    <option value="1">July 19</option>
                    <option value="2">Jun 19</option>
                </select>
            </div>
        </div>
    </div>
</div>
<br />

<div class="card-body">
    <h3 class="text-dark text-uppercase card-title">Orders</h3>
    @if (TempData["Delivery"] != null)
    {
    <div class="alert alert-success alert-dismissible bg-success text-white border-0 fade show" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        @TempData["Delivery"]
    </div>
    }    
    @if (TempData["DeleteOrder"] != null)
    {
    <div class="alert alert-success alert-dismissible bg-success text-white border-0 fade show" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        @TempData["DeleteOrder"]
    </div>
    }
    <hr />
    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="dataTables_length" id="zero_config_length" style="display:flex"><label style="display:inherit;">Show <select name="zero_config_length" aria-controls="zero_config" class="form-control form-control-sm" style="position: relative; bottom: 3px;"><option value="10">10</option><option value="25">25</option><option value="50">50</option><option value="100">100</option></select> entries</label></div>

        </div>
        <div class="col-sm-12 col-md-6">
            @*<div id="zero_config_filter" class="dataTables_filter" style="text-align: right;">
                <label style="display: flex; align-items: center;justify-content: flex-end;">Search: <input type="search" class="form-control form-control-sm" aria-controls="zero_config" style="width:auto" /></label>
            </div>*@
        </div>
    </div>
    <div class="table-responsive">

        <table class="table">
            <thead class="thead-light">
                <tr>
                    <th scope="col" class="text-center">Order Id</th>
                    <th class="text-center">Orderer</th>
                    <th class="text-center">Order Date</th>
                    <th class="text-center">Status</th>
                    <th class="text-center">Delivery Date</th>
                    <th class="text-center">Delivery Status</th>
                    <th class="text-center" width="250px">Feature</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var i in Model)
                {
                    <tr>
                        <td class="text-center font-weight-medium text-dark px-2 py-4">
                            <a href="@Url.Action("InvoinceDetail", "CRUDinvoince", new { invoinceNo = i.invoinceNo})">#@i.invoinceNo</a>
                        </td>

                        <td class="text-muted px-2 py-4 text-center">
                            @if (i.customerId != null)
                             {
                                @Html.DisplayFor(modelItem => i.Customer.firstName)<span> </span>@Html.DisplayFor(modelItem => i.Customer.lastName)
                             }
                            else 
                            {
                                @Html.DisplayFor(modelItem => i.Member.firstName)<span> </span>@Html.DisplayFor(modelItem => i.Member.lastName)
                            }
                        </td>
                        <td class="text-muted px-2 py-4 font-14 text-center">
                            @i.dateOrder
                        </td>
                        <td class="text-center px-2 py-4">
                            @if (i.status == true)
                             {
                                <i class="fa fa-circle text-success font-12" data-toggle="tooltip" data-placement="top" title="Checked"></i>
                             }
                            else
                            {
                                <i class="fa fa-circle text-danger font-12" data-toggle="tooltip" data-placement="top" title="Cancel"></i>
                            }
                        </td>
                        <td class="text-muted px-2 py-4 font-14 text-center">
                            @if (i.deliveryDate == null)
                             {
                                <span>Q/A</span>
                             }
                            else
                            { 
                                @i.deliveryDate
                            }
                        </td>
                        <td class="text-center text-muted font-weight-medium px-2 py-4">
                            @if (i.deliveryStatus == true)
                             {
                                <i class="fa fa-circle text-success font-12" data-toggle="tooltip" data-placement="top" title="Done"></i>
                             }
                            else
                            { 
                                <i class="fa fa-circle text-danger font-12" data-toggle="tooltip" data-placement="top" title="In Progress"></i>
                            }
                        </td>
                        <td class="text-muted px-2 py-4 text-right">
                            @if (i.deliveryStatus != true)
                             {
                                <a href="@Url.Action("DeliverySuccess", "CRUDinvoince", new { id = i.invoinceNo})" class="btn waves-effect waves-light btn-success">Delivery confirm</a>
                             }
                                <a href="@Url.Action("Delete", "CRUDinvoince", new { id = i.invoinceNo})" class="btn waves-effect waves-light btn-danger" onclick="return confirm('Are you sure you want to delete this?')">Delete</a>
                        </td>
                    </tr>
                }

            </tbody>
        </table>
    </div>

    <div class="row" style=" align-items: center">
        <div class="col-sm-12 col-md-5">
            <div class="dataTables_info" id="zero_config_info" role="status" aria-live="polite">Showing 1 to 10 of 57 entries</div>
        </div>
        <div class="col-sm-12 col-md-7">
            <div class="dataTables_paginate paging_simple_numbers" id="default_order_paginate">
                @Html.PagedListPager(Model, page => Url.Action("Index", new { page = page }), new PagedListRenderOptions() { LiElementClasses = new List<string> { "paginate_button", "page-item" } })
            </div>
        </div>
    </div>
</div>

<style>
    .page-item a {
        display: block;
        padding: .5rem .75rem;
        margin-left: -1px;
        line-height: 1.25;
        color: #5f76e8;
        background-color: #fff;
        border: 1px solid #dee2e6;
    }

    .pagination {
        margin: 2px 0;
        white-space: nowrap;
        justify-content: flex-end;
    }
</style>

Project/ShopOnline/ShopOnline/Areas/Admin/Views/CRUDinvoince/InvoinceDetail.cshtml
@using ShopOnline.Models
@model List<InvoinceDetail>
@{
    ViewBag.Title = "InvoinceDetail";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutDashBoard.cshtml";
}
@{
    Invoince info = (Invoince)@Session["information"];
}

<div class="jumbotron jumbotron-fluid">
    <h1 class="mt-3 theme-color mb-4 text-center">Orders detail</h1>
    <p class="lead text-center">
        Orders / #@ViewBag.invoinceNo
    </p>
    <p class="lead text-center">
        <a class="btn btn-primary btn-lg" href="~/Admin/CRUDinvoince/Index" role="button">Back to list</a>
    </p>
</div>
<div class="card-body">
    <h3 class="mb-3 text-dark text-uppercase">Information</h3>
    <hr />
    <table class="table">
        <thead class="thead-light">
            <tr>
                <th scope="col" class="text-center">Name</th>
                <th scope="col" class="text-center">Email</th>
                <th scope="col" class="text-center">Phone</th>
                <th scope="col" class="text-center">Address</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td class="text-center">
                    @if (info.customerId != null && info.userName == null)
                    {
                        @info.Customer.firstName<span> </span>@info.Customer.lastName
                    }
                    else
                    { 
                        @info.Member.firstName<span> </span>@info.Member.lastName
                    }
                </td>
                <td class="text-center">
                    @if (info.customerId != null && info.userName == null)
                    {
                        @info.Customer.email
                    }
                    else
                    { 
                        @info.Member.email
                    }
                </td>
                <td class="text-center">
                    @if (info.customerId != null && info.userName == null)
                    {
                        @info.Customer.phone
                    }
                    else
                    {
                        @info.Member.phone
                    }
                </td>
                <td class="text-center">
                    @if (info.customerId != null && info.userName == null)
                    {
                        @info.Customer.address
                    }
                    else
                    { 
                        @info.Member.address
                    }
                </td>
            </tr>

        </tbody>
    </table>

    <h3 class="mb-3 text-dark text-uppercase">Product</h3>
    <hr />
    <table class="table">
        <thead class="thead-light">
            <tr>
                <th scope="col" class="text-center">STT</th>
                <th scope="col" class="text-center">Product</th>
                <th scope="col" class="text-center">Quality</th>
                <th scope="col" class="text-center">Unit price</th>
                <th scope="col" class="text-center">Discount</th>
                <th scope="col" class="text-center">Total money</th>
            </tr>
        </thead>
        <tbody>
            @{ int stt = 1, total = 0, totaldiscount = 0, totalprice = 0, tempPrice = 0;}
            @foreach (var i in Model)
            {
                tempPrice = (int)i.totalPrice + (int)i.totalDiscount;
                <tr>
                    <th scope="row" class="text-center font-weight-medium" width="80px">@stt</th>
                    <td width="400px">
                        <div class="row">
                            <div class="col-md-3">
                                <img src=@Url.Content("" + i.Product.image) width="80%" />
                            </div>
                            <div class="col-md-9">
                                @i.Product.productName
                            </div>
                        </div>
                    </td>
                    <td class="text-center">@i.quanlityProduct</td>
                    <td class="text-center">$@i.Product.price</td>
                    <td class="text-center">@i.Product.discount%</td>
                    <td class="text-center">$@tempPrice</td>
                </tr>
                stt++;
                total += (int)i.totalPrice;
                totaldiscount += (int)i.totalDiscount;
            }
            @{ 
                totalprice = total + totaldiscount; 
             }
        </tbody>
    </table>

    <h3 class="mb-3 text-dark text-uppercase">Payment</h3>
    <hr />
    <table class="table">
        <thead class="thead-light">
            <tr>
                <th scope="col" class="text-center">Total product money</th>
                <th scope="col" class="text-center">Shipping</th>
                <th scope="col" class="text-center">Total money discounted</th>
                <th scope="col" class="text-center">Total payment</th>
                <th scope="col" class="text-center">Print order</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td class="text-center">$@totalprice</td>
                <td class="text-center">$0</td>
                <td class="text-center">-$@totaldiscount</td>
                <td class="text-center">$@total</td>
                <td class="text-center"><a href="@Url.Action("ExportPDF", "CRUDinvoince")"><u>Print order</u></a></td>
            </tr>
        </tbody>
    </table>

</div>